#Checking Torch

In [2]:
import torch
print(torch.__version__)

2.6.0+cu124


In [3]:
if torch.cuda.is_available():
    print("GPU")
else:
    print("CPU")

GPU


#Creating a Tensor

In [4]:
#empty tensor
empty = torch.empty(2,2)
empty

tensor([[0.9543, 0.0000],
        [0.0000, 0.0000]])

In [5]:
empty.shape
type(empty)

torch.Tensor

In [6]:
#using zeros
zero = torch.zeros(2,2)
zero

tensor([[0., 0.],
        [0., 0.]])

In [7]:
#using ones
one = torch.ones(2,2)
one

tensor([[1., 1.],
        [1., 1.]])

In [8]:
#rand
torch.rand(2,2)

tensor([[0.9432, 0.7805],
        [0.8615, 0.2922]])

In [9]:
#use of seed
torch.rand(2,2)

tensor([[0.2941, 0.4401],
        [0.1935, 0.4905]])

In [10]:
#manual seed
torch.manual_seed(100)
torch.rand(2,2)

tensor([[0.1117, 0.8158],
        [0.2626, 0.4839]])

In [11]:
torch.manual_seed(100)
torch.rand(2,2)

tensor([[0.1117, 0.8158],
        [0.2626, 0.4839]])

In [12]:
#using tensor
torch.tensor([[1,1],[2,3]])

tensor([[1, 1],
        [2, 3]])

#Tensor Shapes

In [13]:
x = torch.tensor([[1,2,3], [4,5,6]])
x.shape

torch.Size([2, 3])

In [14]:
torch.empty_like(x)

tensor([[3616445622929465956, 6068091618163961141, 4121139129909653810],
        [6500726371045617966, 7309453675965983778, 8315168162784306286]])

In [15]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [16]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [17]:
torch.rand_like(x.to(torch.float64))

tensor([[0.4120, 0.1015, 0.6642],
        [0.9736, 0.6941, 0.3464]], dtype=torch.float64)

#Datatypes

In [18]:
x = torch.tensor([[1,2,3], [4,5,6]])
type(x)

torch.Tensor

In [19]:
#find dtype
x.dtype

torch.int64

In [20]:
#assign dtype
y = torch.tensor([1,2,3], dtype=torch.float32)
y

tensor([1., 2., 3.])

In [21]:
#using to()
y.to(torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

Maths ops

Scalar

In [22]:
x = torch.rand(2,2)
x

tensor([[0.9969, 0.7565],
        [0.2239, 0.3023]])

In [23]:
x+2

tensor([[2.9969, 2.7565],
        [2.2239, 2.3023]])

In [24]:
x-2

tensor([[-1.0031, -1.2435],
        [-1.7761, -1.6977]])

In [25]:
x*2

tensor([[1.9938, 1.5130],
        [0.4478, 0.6047]])

In [26]:
x/2

tensor([[0.4984, 0.3783],
        [0.1119, 0.1512]])

In [27]:
(x*100)%2

tensor([[1.6886, 1.6515],
        [0.3894, 0.2346]])

In [28]:
x**2

tensor([[0.9938, 0.5723],
        [0.0501, 0.0914]])

In [29]:
x ## No change original

tensor([[0.9969, 0.7565],
        [0.2239, 0.3023]])

Element wise operation

In [30]:
a , b = torch.rand(2,2)
print(a,b)

tensor([0.1784, 0.8238]) tensor([0.5557, 0.9770])


In [31]:
a+b ### same same

tensor([0.7342, 1.8009])

Reduction Ops

In [32]:
z = torch.randint(size = (2,3), low = 0, high= 20)
z

tensor([[ 0, 11,  9],
        [ 9, 18, 10]])

In [33]:
torch.sum(z)

tensor(57)

In [34]:
torch.sum(z, dim=0)

tensor([ 9, 29, 19])

In [35]:
torch.mean(z.to(torch.float))

tensor(9.5000)

Inplace ops important as well

#GPU tensors

In [36]:
torch.cuda.is_available()

True

In [37]:
if torch.cuda.is_available():
    print("GPU available, but we will attempt to use TPU")
else:
    print("GPU not available")

GPU available, but we will attempt to use TPU


In [38]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

Using device: cuda


In [39]:
torch.rand((2,2), device = device)

tensor([[0.3563, 0.0303],
        [0.7088, 0.2009]], device='cuda:0')

In [40]:
# import time

# size = 10000

# mc1 = torch.randn(size, size)
# mc2 = torch.randn(size, size)

# starttime = time.time()

# mc3 = torch.matmul(mc1, mc2)

# endtime = time.time()

# print(f"Time on CPU = {endtime - starttime}")

# mg1 = mc1.to(device)
# mg2 = mc2.to(device)

# starttime = time.time()

# mg3 = torch.matmul(mg1, mg2)

# endtime = time.time()

# print(f"Time on GPU = {endtime - starttime}")


Reshaping Tensors

#AUTOGRAD

In [41]:
import torch
import math

In [42]:
x = torch.tensor(3.0, requires_grad=True)
x

tensor(3., requires_grad=True)

In [43]:
y = x**2
y

tensor(9., grad_fn=<PowBackward0>)

In [44]:
y.backward()

In [45]:
x.grad

tensor(6.)

more example

In [46]:
x = torch.tensor(3.0, requires_grad=True)
x

tensor(3., requires_grad=True)

In [47]:
y = x**2
y

tensor(9., grad_fn=<PowBackward0>)

In [48]:
z = torch.sin(y)
z

tensor(0.4121, grad_fn=<SinBackward0>)

In [49]:
z.backward()

In [50]:
x.grad

tensor(-5.4668)

#Perceptron Example for AUTOGRAD

In [53]:
x = torch.tensor(6.7) #input tensor
y = torch.tensor(0.0) #True label

w = torch.tensor(1.0)
b = torch.tensor(0.0)

In [54]:
#binary cross entropy for scalar
def bce(pred, target):
    epsilion = 1e-8
    pred = torch.clamp(pred, epsilion, 1-epsilion)
    return -(target*torch.log(pred) + (1-target)*torch.log(1-pred))

In [55]:
#forward pass
z = w*x + b
y_pred = torch.sigmoid(z)

loss = bce(y_pred, y)

In [57]:
loss

tensor(6.7012)

In [58]:
#Derivatives/ Backprop
#Manual - skip

# Auto grad
x = torch.tensor(6.7) #input tensor
y = torch.tensor(0.0) #True label

#We didnot put requiresgrad true bcz we dont need it with respect to x or y, we need wrt w,b

w = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

In [59]:
w

tensor(1., requires_grad=True)

In [60]:
b

tensor(0., requires_grad=True)

In [63]:
#forward
z = w*x + b
z

tensor(6.7000, grad_fn=<AddBackward0>)

In [64]:
y_pred = torch.sigmoid(z)
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [66]:
loss = bce(y_pred, y)
loss

tensor(6.7012, grad_fn=<NegBackward0>)

In [67]:
loss.backward()

In [68]:
w.grad

tensor(6.6918)

In [69]:
b.grad

tensor(0.9988)

Cleaning Gradients