In [64]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
import torch

Understanding training pipeline with real world dataset

Getting data

In [65]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')

In [66]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,radius_se,texture_se,perimeter_se,area_se,smoothness_se,compactness_se,concavity_se,concave points_se,symmetry_se,fractal_dimension_se,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,1.0950,0.9053,8.589,153.40,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,0.5435,0.7339,3.398,74.08,0.005225,0.01308,0.01860,0.01340,0.01389,0.003532,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,0.7456,0.7869,4.585,94.03,0.006150,0.04006,0.03832,0.02058,0.02250,0.004571,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,0.4956,1.1560,3.445,27.23,0.009110,0.07458,0.05661,0.01867,0.05963,0.009208,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,0.7572,0.7813,5.438,94.44,0.011490,0.02461,0.05688,0.01885,0.01756,0.005115,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [67]:
df.describe()

,id,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,radius_se,texture_se,perimeter_se,area_se,smoothness_se,compactness_se,concavity_se,concave points_se,symmetry_se,fractal_dimension_se,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
count,5.690000e+02,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,0.0
mean,3.037183e+07,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919,0.181162,0.062798,0.405172,1.216853,2.866059,40.337079,0.007041,0.025478,0.031894,0.011796,0.020542,0.003795,16.269190,25.677223,107.261213,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946,NaN
std,1.250206e+08,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803,0.027414,0.007060,0.277313,0.551648,2.021855,45.491006,0.003003,0.017908,0.030186,0.006170,0.008266,0.002646,4.833242,6.146258,33.602542,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061,NaN
min,8.670000e+03,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,0.049960,0.111500,0.360200,0.757000,6.802000,0.001713,0.002252,0.000000,0.000000,0.007882,0.000895,7.930000,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040,NaN
25%,8.692180e+05,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161900,0.057700,0.232400,0.833900,1.606000,17.850000,0.005169,0.013080,0.015090,0.007638,0.015160,0.002248,13.010000,21.080000,84.110000,515.300000,0.116600,0.147200,0.114500,0.064930,0.250400,0.071460,NaN
50%,9.060240e+05,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500,0.179200,0.061540,0.324200,1.108000,2.287000,24.530000,0.006380,0.020450,0.025890,0.010930,0.018730,0.003187,14.970000,25.410000,97.660000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040,NaN
75%,8.813129e+06,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000,0.195700,0.066120,0.478900,1.474000,3.357000,45.190000,0.008146,0.032450,0.042050,0.014710,0.023480,0.004558,18.790000,29.720000,125.400000,1084.000000,0.146000,0.339100,0.382900,0.161400,0.317900,0.092080,NaN
max,9.113205e+08,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,0.097440,2.873000,4.885000,21.980000,542.200000,0.031130,0.135400,0.396000,0.052790,0.078950,0.029840,36.040000,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500,NaN


In [68]:
df.shape

(569, 33)

In [69]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [70]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,radius_se,texture_se,perimeter_se,area_se,smoothness_se,compactness_se,concavity_se,concave points_se,symmetry_se,fractal_dimension_se,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,1.0950,0.9053,8.589,153.40,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,0.5435,0.7339,3.398,74.08,0.005225,0.01308,0.01860,0.01340,0.01389,0.003532,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,0.7456,0.7869,4.585,94.03,0.006150,0.04006,0.03832,0.02058,0.02250,0.004571,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,0.4956,1.1560,3.445,27.23,0.009110,0.07458,0.05661,0.01867,0.05963,0.009208,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,0.7572,0.7813,5.438,94.44,0.011490,0.02461,0.05688,0.01885,0.01756,0.005115,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


Splitting data

In [71]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[: , 0], test_size= 0.2)

Scaling data

In [72]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [73]:
X_train

array([[-0.29257905,  0.00751113, -0.36911721, ..., -1.54860766,
        -0.73872645, -1.18067204],
       [-0.34008073, -0.24538395, -0.29447693, ..., -0.05437634,
        -0.50338826,  0.32018611],
       [-0.14169135,  0.59450614, -0.18454478, ..., -0.7782039 ,
        -0.7272064 , -0.75704273],
       ...,
       [ 3.25048764, -0.42171447,  3.34626482, ...,  2.46407629,
         1.32007127,  0.27522953],
       [ 1.5963114 ,  0.66643043,  1.55327557, ...,  1.90576872,
        -0.19728404, -0.41641017],
       [-0.84862816, -1.00174907, -0.8202041 , ..., -0.08623628,
         0.67988557,  0.42796663]])

In [74]:
y_train

58     B
518    B
267    B
469    B
340    B
      ..
6      M
543    B
352    M
18     M
342    B
Name: diagnosis, Length: 455, dtype: object

Label Encoder

In [75]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

NP arrays to Tensors

In [76]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)


In [77]:
X_train_tensor

tensor([[-0.2926,  0.0075, -0.3691,  ..., -1.5486, -0.7387, -1.1807],
        [-0.3401, -0.2454, -0.2945,  ..., -0.0544, -0.5034,  0.3202],
        [-0.1417,  0.5945, -0.1845,  ..., -0.7782, -0.7272, -0.7570],
        ...,
        [ 3.2505, -0.4217,  3.3463,  ...,  2.4641,  1.3201,  0.2752],
        [ 1.5963,  0.6664,  1.5533,  ...,  1.9058, -0.1973, -0.4164],
        [-0.8486, -1.0017, -0.8202,  ..., -0.0862,  0.6799,  0.4280]],
       dtype=torch.float64)

In [78]:
X_train_tensor.shape

torch.Size([455, 30])

In [79]:
X_test_tensor.shape

torch.Size([114, 30])

Defining the model - NN

In [80]:
class MySimpleNN():
    
    def __init__(self, X): # X is input data
        
        # Initialize random weights
        self.weights = torch.rand(X.shape[1], 1, dtype= torch.float64, requires_grad= True)
        
        #Initial Bias
        self.bias = torch.zeros(1, dtype= torch.float64, requires_grad= True)
        
        
    def forward(self, X):
        z = torch.matmul(X, self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred
    
    
    def loss(self, y_pred, y):
        epsilon = 1e-8
        y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)
        loss = -(y*torch.log(y_pred) + (1-y)*torch.log(1-y_pred)).mean()
        return loss
    


Important params

In [81]:
lr = 0.1
epochs = 50

Training Pipeline

In [82]:
# 1. Create model
model = MySimpleNN(X_train_tensor)

## These steps in loop - epochs ##

for epoch in range(epochs):    

    # 2. Forward pass
    y_pred = model.forward(X_train_tensor)
    # print(y_pred)
    
    # 3. Loss
    loss = model.loss(y_pred, y_train_tensor)
    
    
    # 4. Back pass
    loss.backward()
    
    # 5. Params update
    with torch.no_grad():
        model.weights -= lr*model.weights.grad
        model.bias -= lr*model.bias.grad
    
    # 6. Zero 
    model.weights.grad.zero_()
    model.bias.grad.zero_()
    
    print(f"Epoch = {epoch + 1}, loss = {loss}")


Epoch = 1, loss = 2.951928720455751
Epoch = 2, loss = 2.795759144130985
Epoch = 3, loss = 2.630386597588412
Epoch = 4, loss = 2.461292175060563
Epoch = 5, loss = 2.293408683910202
Epoch = 6, loss = 2.1253256938584415
Epoch = 7, loss = 1.959377259686692
Epoch = 8, loss = 1.791183846478925
Epoch = 9, loss = 1.6312051228342264
Epoch = 10, loss = 1.477346483837399
Epoch = 11, loss = 1.3364317345877197
Epoch = 12, loss = 1.210426401164902
Epoch = 13, loss = 1.1010846301672061
Epoch = 14, loss = 1.0096508067390166
Epoch = 15, loss = 0.9364579402656562
Epoch = 16, loss = 0.8805476877643649
Epoch = 17, loss = 0.8396283384360232
Epoch = 18, loss = 0.8105557035491257
Epoch = 19, loss = 0.7900770060423484
Epoch = 20, loss = 0.7754258748138174
Epoch = 21, loss = 0.7645636892059197
Epoch = 22, loss = 0.7561278190767923
Epoch = 23, loss = 0.7492597619292389
Epoch = 24, loss = 0.7434352696176206
Epoch = 25, loss = 0.7383379566603642
Epoch = 26, loss = 0.7337761788695178
Epoch = 27, loss = 0.729631689

In [85]:
model.weights

tensor([[-0.1632],
        [ 0.0707],
        [ 0.1768],
        [-0.0384],
        [-0.1631],
        [ 0.3662],
        [-0.0890],
        [-0.3199],
        [-0.1948],
        [-0.0275],
        [ 0.0042],
        [-0.1667],
        [-0.2345],
        [ 0.5368],
        [ 0.1625],
        [ 0.0926],
        [-0.1219],
        [-0.1588],
        [ 0.3613],
        [-0.2360],
        [ 0.1529],
        [ 0.1236],
        [-0.3514],
        [ 0.0902],
        [-0.1097],
        [-0.4344],
        [ 0.1739],
        [ 0.2936],
        [-0.0754],
        [ 0.5000]], dtype=torch.float64, requires_grad=True)

In [86]:
model.bias

tensor([-0.3716], dtype=torch.float64, requires_grad=True)

Evaluation

In [89]:
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.5).float()
    acc = (y_pred == y_test_tensor).float().mean()
    
print(acc)


tensor(0.5512)
