In [1]:
from sklearn.datasets import make_classification
import torch

Creating a synthetic dataset

In [2]:
X,y = make_classification(
    n_samples=10,
    n_features=2,
    n_informative=2,
    n_redundant=0,
    n_classes=2,
    random_state=42
)

In [6]:
X.shape

(10, 2)

In [7]:
y.shape

(10,)

In [8]:
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.long)


In [9]:
from torch.utils.data import DataLoader, Dataset

In [10]:
class CustomDataset(Dataset):
    
    def __init__(self, features, labels):
        
        self.features = features
        self.labels = labels
    
    def __len__(self):
        return self.features.shape[0]
    
    def __getitem__(self, index):
        return self.features[index], self.labels[index]

In [11]:
dataset = CustomDataset(X, y)

In [14]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [15]:
for batch_features, batch_labels in dataloader:
    print(batch_features, batch_labels)

tensor([[-1.1402, -0.8388],
        [ 1.8997,  0.8344]]) tensor([0, 1])
tensor([[-1.9629, -0.9923],
        [ 1.7273, -1.1858]]) tensor([0, 1])
tensor([[-2.8954,  1.9769],
        [-0.9382, -0.5430]]) tensor([0, 1])
tensor([[-0.5872, -1.9717],
        [ 1.0683, -0.9701]]) tensor([0, 1])
tensor([[-0.7206, -0.9606],
        [ 1.7774,  1.5116]]) tensor([0, 1])
