In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
import torch
import torch.nn as nn

Creating model class

In [4]:
class Model(nn.Module):
    
    def __init__(self, num_features):
        super().__init__()
        
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        
        return out
        
        

Creating simple dataset

In [5]:
features = torch.rand(10,5)

Creating model

In [6]:
model = Model(features.shape[1])

Forward pass

In [7]:
model(features)

tensor([[0.4731],
        [0.4998],
        [0.4730],
        [0.4812],
        [0.4849],
        [0.4526],
        [0.4743],
        [0.4690],
        [0.4764],
        [0.5231]], grad_fn=<SigmoidBackward0>)

In [8]:
model.linear.weight

Parameter containing:
tensor([[-0.1061,  0.3043,  0.2385,  0.2307, -0.1620]], requires_grad=True)

In [9]:
model.linear.bias

Parameter containing:
tensor([-0.3099], requires_grad=True)

Visualizing network

In [10]:
%pip install torchinfo

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [11]:
from torchinfo import summary

summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

NN with hidden layers

In [ ]:
# class HModel(nn.Module):
    
#     def __init__(self, num_features):
        
#         super().__init__()
        
#         self.l1 = nn.Linear(num_features, 3)
#         self.relu = nn.ReLU()
#         self.l2 = nn.Linear(3,1)
#         self.sigmoid = nn.Sigmoid()
        
#     def forward(self, features):
        
#         out = self.l1(features)
#         out = self.relu(out)
#         out = self.l2(out)
#         out = self.sigmoid(out)
        
#         return out

# We will use sequencial to containerize the layers
    

In [ ]:

class HModel(nn.Module):
    
    def __init__(self, num_features):
        
        super().__init__()
        
        self.network = nn.Sequential(
            nn.Linear(num_features, 3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
            )
        
        
    def forward(self, features):
        
        out = self.network(features)
        
        return out
    

In [30]:
features = torch.rand(10,5)
features

tensor([[0.4739, 0.8490, 0.6494, 0.8350, 0.2033],
        [0.4500, 0.7341, 0.7575, 0.6047, 0.4861],
        [0.5117, 0.2258, 0.1717, 0.4190, 0.1122],
        [0.8476, 0.8143, 0.5236, 0.7730, 0.1659],
        [0.2381, 0.2541, 0.8391, 0.6418, 0.8887],
        [0.9043, 0.9309, 0.9165, 0.4523, 0.5734],
        [0.4075, 0.2725, 0.8738, 0.0120, 0.5697],
        [0.0162, 0.0758, 0.0127, 0.6914, 0.8854],
        [0.2768, 0.2737, 0.0254, 0.1879, 0.8116],
        [0.0765, 0.9756, 0.5025, 0.1430, 0.5756]])

In [31]:
hmodel = HModel(features.shape[1])

In [32]:
hmodel(features)

tensor([[0.6312],
        [0.6312],
        [0.6489],
        [0.6312],
        [0.6312],
        [0.6371],
        [0.6568],
        [0.6376],
        [0.6595],
        [0.6478]], grad_fn=<SigmoidBackward0>)

In [33]:
summary(hmodel, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
HModel                                   [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00