Checking Torch

In [1]:
import torch
print(torch.__version__)

2.6.0+cu124


In [2]:
if torch.cuda.is_available():
    print("GPU")
else:
    print("CPU")

GPU


Creating a Tensor

In [3]:
#empty tensor
empty = torch.empty(2,2)
empty

tensor([[1.4929e-21, 0.0000e+00],
        [2.0519e-21, 0.0000e+00]])

In [4]:
empty.shape
type(empty)

torch.Tensor

In [5]:
#using zeros
zero = torch.zeros(2,2)
zero

tensor([[0., 0.],
        [0., 0.]])

In [6]:
#using ones
one = torch.ones(2,2)
one

tensor([[1., 1.],
        [1., 1.]])

In [7]:
#rand
torch.rand(2,2)

tensor([[0.6473, 0.3528],
        [0.4120, 0.6681]])

In [8]:
#use of seed
torch.rand(2,2)

tensor([[0.5765, 0.8471],
        [0.6710, 0.0523]])

In [9]:
#manual seed
torch.manual_seed(100)
torch.rand(2,2)

tensor([[0.1117, 0.8158],
        [0.2626, 0.4839]])

In [10]:
torch.manual_seed(100)
torch.rand(2,2)

tensor([[0.1117, 0.8158],
        [0.2626, 0.4839]])

In [11]:
#using tensor
torch.tensor([[1,1],[2,3]])

tensor([[1, 1],
        [2, 3]])

Tensor Shapes

In [12]:
x = torch.tensor([[1,2,3], [4,5,6]])
x.shape

torch.Size([2, 3])

In [13]:
torch.empty_like(x)

tensor([[3616445622929465956, 6068091618163961141, 3761977068200014384],
        [6500437203917222446, 7309453675965983778, 8315168162784306286]])

In [14]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [15]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [16]:
torch.rand_like(x.to(torch.float64))

tensor([[0.4120, 0.1015, 0.6642],
        [0.9736, 0.6941, 0.3464]], dtype=torch.float64)

Datatypes

In [17]:
x = torch.tensor([[1,2,3], [4,5,6]])
type(x)

torch.Tensor

In [18]:
#find dtype
x.dtype

torch.int64

In [19]:
#assign dtype
y = torch.tensor([1,2,3], dtype=torch.float32)
y

tensor([1., 2., 3.])

In [20]:
#using to()
y.to(torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

Maths ops

Scalar

In [21]:
x = torch.rand(2,2)
x

tensor([[0.9969, 0.7565],
        [0.2239, 0.3023]])

In [22]:
x+2

tensor([[2.9969, 2.7565],
        [2.2239, 2.3023]])

In [23]:
x-2

tensor([[-1.0031, -1.2435],
        [-1.7761, -1.6977]])

In [24]:
x*2

tensor([[1.9938, 1.5130],
        [0.4478, 0.6047]])

In [25]:
x/2

tensor([[0.4984, 0.3783],
        [0.1119, 0.1512]])

In [26]:
(x*100)%2

tensor([[1.6886, 1.6515],
        [0.3894, 0.2346]])

In [27]:
x**2

tensor([[0.9938, 0.5723],
        [0.0501, 0.0914]])

In [28]:
x ## No change original

tensor([[0.9969, 0.7565],
        [0.2239, 0.3023]])

Element wise operation

In [29]:
a , b = torch.rand(2,2)
print(a,b)

tensor([0.1784, 0.8238]) tensor([0.5557, 0.9770])


In [30]:
a+b ### same same

tensor([0.7342, 1.8009])

Reduction Ops

In [31]:
z = torch.randint(size = (2,3), low = 0, high= 20)
z

tensor([[ 0, 11,  9],
        [ 9, 18, 10]])

In [32]:
torch.sum(z)

tensor(57)

In [33]:
torch.sum(z, dim=0)

tensor([ 9, 29, 19])

In [34]:
torch.mean(z.to(torch.float))

tensor(9.5000)

Inplace ops important as well

GPU tensors

In [35]:
torch.cuda.is_available()

True

In [37]:
if torch.cuda.is_available():
    print("GPU available, but we will attempt to use TPU")
else:
    print("GPU not available")

GPU available, but we will attempt to use TPU


In [38]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

Using device: cuda


In [39]:
torch.rand((2,2), device = device)

tensor([[0.3563, 0.0303],
        [0.7088, 0.2009]], device='cuda:0')

In [40]:
import time

size = 10000

mc1 = torch.randn(size, size)
mc2 = torch.randn(size, size)

starttime = time.time()

mc3 = torch.matmul(mc1, mc2)

endtime = time.time()

print(f"Time on CPU = {endtime - starttime}")

mg1 = mc1.to(device)
mg2 = mc2.to(device)

starttime = time.time()

mg3 = torch.matmul(mg1, mg2)

endtime = time.time()

print(f"Time on GPU = {endtime - starttime}")


Time on CPU = 26.6999294757843
Time on GPU = 0.13218045234680176


Reshaping Tensors